spring:
  application:
    name: lab-manager-backend

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kube:
  configPath: "/.kube/config"

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}
  access-token-expires: 900000        # 15?
  refresh-token-expires: 1209600000   # 14?

cors:
  allowed-origins:
    - "http://localhost:3000"

lab:
  base-workspace: labmanager